language: php
sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

cache:
  apt: true
  directories:
    - tests/node/node_modules
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
